services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: teer_db
    environment:
      POSTGRES_DB: teer_betting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.py:/docker-entrypoint-initdb.d/init_db.py
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d teer_betting"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: teer_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/teer_betting
      - SECRET_KEY=your-super-secret-key-change-in-production-$(date +%s)
      - DEBUG=True
      - BACKEND_CORS_ORIGINS=https://effective-waddle-x5477gpx75g6cvj45-80.app.github.dev,https://effective-waddle-x5477gpx75g6cvj45-3000.app.github.dev,http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://localhost,http://127.0.0.1:80,http://127.0.0.1,http://frontend:80,http://teer_frontend:80,http://165.22.61.56:3000,http://165.22.61.56:80,http://165.22.61.56
      - ALLOWED_ORIGINS=https://effective-waddle-x5477gpx75g6cvj45-80.app.github.dev,https://effective-waddle-x5477gpx75g6cvj45-3000.app.github.dev,http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://localhost,http://127.0.0.1:80,http://127.0.0.1,http://frontend:80,http://teer_frontend:80,http://165.22.61.56:3000,http://165.22.61.56:80,http://165.22.61.56
      - VPS_IP=165.22.61.56
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 40s

  # React Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: /api/v1
    container_name: teer_frontend
    environment:
      - REACT_APP_API_BASE_URL=/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend

  # Redis (for future caching/sessions)
  redis:
    image: redis:7-alpine
    container_name: teer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # pgAdmin (for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: teer_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@teer.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    name: teer_network