#!/bin/bash

# Quick VPS Deployment Summary for 178.128.61.118
# Run this script to get deployment commands

echo "🚀 TEER BETTING APP - VPS DEPLOYMENT (178.128.61.118)"
echo "=================================================="
echo ""
echo "📋 STEP-BY-STEP DEPLOYMENT:"
echo ""
echo "1️⃣  SSH into your VPS:"
echo "   ssh root@178.128.61.118"
echo ""
echo "2️⃣  Run VPS setup (first time only):"
echo "   curl -fsSL https://raw.githubusercontent.com/rtsant123/teer-betting-app/main/vps-setup.sh -o vps-setup.sh"
echo "   chmod +x vps-setup.sh"
echo "   ./vps-setup.sh"
echo ""
echo "3️⃣  Switch to deploy user:"
echo "   sudo su - deploy"
echo "   cd /home/deploy/teer-betting-app"
echo ""
echo "4️⃣  Deploy the application:"
echo "   ./deploy-production-vps.sh"
echo ""
echo "🎯 ACCESS YOUR APP:"
echo "   Frontend: http://178.128.61.118"
echo "   Admin:    http://178.128.61.118/admin"
echo "   API:      http://178.128.61.118:8000/api/v1/docs"
echo ""
echo "✅ OPTIMIZATIONS INCLUDED:"
echo "   • 1GB RAM optimized containers"
echo "   • Fixed CORS for VPS IP"
echo "   • Centralized API endpoints"
echo "   • Transaction details in admin"
echo "   • Security hardening"
echo "   • Resource monitoring"
echo ""
echo "🔧 USEFUL COMMANDS:"
echo "   docker stats                                    # Monitor resources"
echo "   docker-compose -f docker-compose.prod-optimized.yml logs -f  # View logs"
echo "   docker-compose -f docker-compose.prod-optimized.yml restart  # Restart"
echo ""
