global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Backend
  - job_name: 'teer-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Frontend
  - job_name: 'teer-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'teer-database'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'teer-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules (create alerts.yml)
# groups:
#   - name: teer-betting-alerts
#     rules:
#       - alert: HighErrorRate
#         expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
#         for: 5m
#         labels:
#           severity: warning
#         annotations:
#           summary: "High error rate detected"
#           description: "Error rate is above 10% for 5 minutes"
#       
#       - alert: DatabaseDown
#         expr: up{job="teer-database"} == 0
#         for: 1m
#         labels:
#           severity: critical
#         annotations:
#           summary: "Database is down"
#           description: "PostgreSQL database is not responding"